version: '3'  
services:

  db:
    #image: postgres
    image: postgres:14.2
    environment: 
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

  keycloak:
    #image: jboss/keycloak
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloakdb
      DB_USER: postgres
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/demo/certs/localhostcert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/demo/certs/localhostkey.pem
#      REGISTRY_AUTH_TOKEN_REALM: https://localhost:8843/auth/realms/Servicios/protocol/openid-connect/auth
#      REGISTRY_AUTH_TOKEN_SERVICE: docker-test
#      REGISTRY_AUTH_TOKEN_ISSUER: https://localhost:8843/realms/Servicios
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
    ports:
      - '8083:8080'
      - '8843:8443'
    depends_on:
      - db
    volumes:
      - ./certs:/opt/keycloak/demo/certs

volumes:  
  db:
    driver: local
