version: '3'  
services:

  db:
    #image: postgres
    image: postgres:14.2
    environment: 
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

  keycloak:
    #image: jboss/keycloak
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloakdb
      DB_USER: postgres
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/demo/certs/localhostcert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/demo/certs/localhostkey.pem
#      REGISTRY_AUTH_TOKEN_REALM: https://localhost:8843/auth/realms/Servicios/protocol/openid-connect/auth
#      REGISTRY_AUTH_TOKEN_SERVICE: docker-test
#      REGISTRY_AUTH_TOKEN_ISSUER: https://localhost:8843/realms/Servicios
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
    ports:
      - '8083:8080'
      - '8843:8443'
    command:
      - "-b 0.0.0.0"
    depends_on:
      - db
    volumes:
      - ./certs:/opt/keycloak/demo/certs
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

#  db_w:
#    image: mysql:5.7
#    volumes:
#      - db_w_data:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: somewordpress
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress

#  proxy:
#    image: nginx
#    ports:
#      - 8085:80
#      - 8543:443
#    volumes:
#      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
#      - ./proxy/certs:/etc/nginx/certs
#    depends_on:
#      - wordpress

#  wordpress:
#    depends_on:
#      - db_w
#    image: wordpress:latest
#    volumes:
#      - wordpress_data:/var/www/html
#    ports:
#      - "8010:80"
#    restart: always
#    environment:
#      WORDPRESS_DB_HOST: db_w:3306
#      WORDPRESS_DB_USER: wordpress
#      WORDPRESS_DB_PASSWORD: wordpress
#      WORDPRESS_DB_NAME: wordpress
#    extra_hosts:
#      - "host.docker.internal:host-gateway"


networks:
  db:
    driver: bridge
#  db_w:       
#    driver: bridge
  keycloak:       
    driver: bridge
#  wordpress:       
#    driver: bridge
volumes:  
  db:
    driver: local
#  db_w_data: {}
#  wordpress_data: {}
